// experimental/svelte/src/base/Link.svelte
<script>
  import Icon from './Icon'

  const {
    as,
    to,
    children,
    text,
    icon,
    iconAfter,
    blank,
    label,
    preventDefaultFocus,
    ...props
  } = $$props

  const Shell = as || (to ? 'a' : 'button')

  const onMousedown = e => {
    if (preventDefaultFocus)
      e.preventDefault()
  }
</script>

<Shell
  on:mousedown={onMousedown}
  href={to}
  target={blank && '_blank'}
  rel={blank && 'noopener noreferrer'}
  aria-label={label || text}
  {...props}
>
  {#if icon}
    <Icon {...icon} />
  {/if}
  {children}
  {#if text}
    <span>{text}</span>
  {/if}
  {#if iconAfter}
    <Icon {...iconAfter} />
  {/if}
</Shell>

// fernui-react/src/Link.js
import React from 'react'
import Cond from './Cond'
import Icon from './Icon'

export default function Link({
  as,
  to,
  text,
  icon,
  iconClass,
  blank,
  label,
  children,
  ...props
}) {
  return (
    <Cond
      as={as || (to ? 'a' : 'button')}
      href={to}
      target={blank && '_blank'}
      rel={blank && 'noopener noreferrer'}
      aria-label={label || text}
      {...props}
    >
      <Cond hide={!text} as='span'>
        {text}
      </Cond>
      {children}
      {icon && <Icon i={icon} className={iconClass} />}
    </Cond>
  )
}
