// experimental/svelte/src/base/Avatar.svelte
<script>
  import { cn } from '@fernui/util'
  import Media from './Media'
  import Icon from './Icon'
  import { profile } from '../icons'

  const defaultColors = letter => (
    'JWHF'.includes(letter) ? '#bb2e94' :   // red
    'SLEIQM'.includes(letter) ? '#7d2b9c' : // purple
    'DRVYOP'.includes(letter) ? '#2d4baf' : // blue
    'CKZXG'.includes(letter) ? '#1c7963' :  // aqua
    '#469310'                               // green 
  )

  const _letterStyle = (firstLetter, colors) => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors(firstLetter),
  })

  const { title, src, colors = defaultColors, classes, ...props } = $$props

  const firstLetter = title?.substring(0, 1).toUpperCase()
  const { as, innerClass, placeholder, cover, lazy, ...nonMediaProps } = props

  let validSrc = !!src
</script>

{#if validSrc}
  <Media
    src={src}
    alt={title}
    classes={cn('fui-avatar', classes)}
    onError={() => validSrc = false}
    {...props}
  />
{:else if firstLetter}
  <div
    class={cn('fui-avatar', classes)}
    style={_letterStyle(firstLetter, colors)}
    {...nonMediaProps}
  >
    {firstLetter}
  </div>
{:else}
  <Icon
    i={profile}
    className={cn('fui-avatar', classes)}
    {...nonMediaProps}
  />
{/if}

// packages/react/src/base/Avatar.js
import React from 'react';
import { Media, Icon } from '..';
import { profile } from '../icons';
export default function Avatar({ title, src, ...props }) {
    const firstLetter = title?.substring(0, 1).toUpperCase();
    return src ? (React.createElement(Media, { src: src, alt: title, ...props })) : firstLetter ? (React.createElement("div", { style: letterStyle(firstLetter), ...props }, firstLetter)) : (React.createElement(Icon, { i: profile, style: { aspectRatio: '1' }, ...props }));
}
const letterStyle = (firstLetter) => ({
    aspectRatio: '1/1',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors(firstLetter),
});
const colors = (l) => ('JWHF'.includes(l) ? 'hsl(34, 82%, 60%)' : // orange
    'SLEIQM'.includes(l) ? 'hsl(133, 56%, 55%)' : // green
        'DRVYOP'.includes(l) ? 'hsl(182, 56%, 54%)' : // aqua
            'CKZXG'.includes(l) ? 'hsl(218, 59%, 56%)' : // blue
                'BATUN'.includes(l) ? 'hsl(325, 58%, 60%)' : '' // violet
);
